apiVersion:  backstage.io/v1alpha1
kind: Component
metadata:
  name: NodejsApp
  description: This is a sample Nodejs app deployment
  tags:
    - node
    - web
    - express
spec:
  type: service
  lifecycle: experimental
  owner: kosli
