site_name: 'NodejsApp'
site_description: 'This is a sample Nodejs service that exposes a User Api'
repo_url: https://github.com/officialsamtech/nodejs-app

plugins: 
  - techdocs-core

nav:
  - Home: index.md
  - API Reference: api.md
  - User Guide: usage.md