name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      # Continue with other steps such as installing dependencies and running tests
      - run: yarn install --frozen-lockfile
